name: first_game
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: 8.0.2
  flame: 1.0.0
  flame_audio: 1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  flutter_localizations:
    sdk: flutter
  fps_widget: ^1.0.1+1
  intl: 0.17.0

dev_dependencies:
  bloc_test: 9.0.2
  flame_lint: 0.0.1
  flame_test: 1.1.0
  flutter_test:
    sdk: flutter
  mocktail: 0.2.0
  very_good_analysis: 2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/audio/
