name: first_game

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.0"
          channel: "stable"
          cache: true
          cache-key: "${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pubspec.lock') }}"
          cache-path: |
            "./.dart_tool"
            "~/.pub-cache"

      - name: Install Dependencies
        run: |
          flutter pub global activate very_good_cli
          very_good --analytics false
          very_good packages get --recursive

      - name: Debug
        run: |
          ls -a ~/.pub-cache
          ls -a ./.dart_tool

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: true
          fatal-warnings: true
          annotate: true
          annotate-only: false
          working-directory: .

      - name: Verify
        run: flutter test -t presubmit-only

      - name: Run tests
        run: flutter test -x presubmit-only --no-pub --coverage --test-randomize-ordering-seed random

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          exclude: "**/*.g.dart **/*.gen.dart **/l10n/*.dart **/l10n/**/*.dart **/*camera_repository_platform.dart **/*camera_repository_controller.dart **/*analyzer.dart **/main/bootstrap.dart"
          path: coverage/lcov.info

      - name: Generate Visual Architecture
        env:
          FLUTTER_DART_HOME: $/bin/cache/dart-sdk/bin
          FLUTTER_PUB_CACHE: $/.pub-cache/bin
        run: |
          flutter pub global activate pubviz
          export PATH=$PATH:$FLUTTER_DART_HOME
          export PATH=$PATH:$FLUTTER_PUB_CACHE
          pubviz print -d > pubviz.html

      - name: Upload Visual Architecture Artifact
        uses: actions/upload-artifact@v1
        with:
          name: visual-architecture-report
          path: ./pubviz.html

      - name: Debug
        run: |
          ls -a ~/.pub-cache
          ls -a ./.dart_tool
          echo $PUB_CACHE