name: mario_cli

pull_request:
    paths:
      - ".github/workflows/main.yaml"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/main.yaml"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.0"
          channel: "stable"
          cache: true
          cache-key: "${{ runner.os }}-build-${{ hashFiles('**/pubspec.lock') }}"
          cache-path: |
            ./.dart_tool
            ~/.pub-cache

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: flutter format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze lib test

      - name: Verify Build
        run: flutter pub run test --run-skipped -t pull-request-only

      - name: Run Tests
        run: flutter test -x pull-request-only -x e2e --no-pub --coverage --test-randomize-ordering-seed random

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0